import Head from "next/head";
import styles from "../../styles/netflix/Home.module.css";
 
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GoChen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
        ready to run!!!
      </main>
    </div>
  );
}
