import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner/banner";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GoChen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner />
        ready to run!!!
      </main>
    </div>
  );
}
