import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner/banner";
import Link from "next/link";
import { SyntheticEvent } from "react";
import router from "next/router";
export default function Home() {
  const handleOnClickHome = (e: SyntheticEvent) => {
    e.preventDefault();
    router.push("/youflix/");
  };

  const handleOnClickMyList = (e:SyntheticEvent) => {
    e.preventDefault();
    router.push("/coffee-store");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>GoChen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
      <ul className={styles.navItems}>
          {/* <li className={styles.navItem} onClick={handleOnClickHome}>
            go to the movies
          </li> */}
          <li className={styles.navItem2} onClick={handleOnClickMyList}>
            grab a coffee
          </li>
        </ul>
        <Banner />
        ready to run!!!
      </main>
    </div>
  );
}
